# Generated by Django 4.2.5 on 2023-10-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastrados',
            fields=[
                ('id_cadastrados', models.AutoField(primary_key=True, serialize=False)),
                ('gas', models.TextField(max_length=255)),
                ('energia', models.TextField(max_length=255)),
                ('agua', models.TextField(max_length=255)),
                ('comida', models.TextField(max_length=255)),
                ('aluguel', models.TextField(max_length=255)),
                ('outros', models.TextField(max_length=255)),
            ],
        ),
    ]
